const Lang = [
  {
    id: 'เลขที่',
    name: 'ชื่อ',
    memo: 'หมายเหตุ',
    date: 'วันที่',
    lang: 'ไทย',
    dashboard: 'แผงควบคุม',
    creates: 'สร้าง',
    products: 'เพิ่มรายการสินค้า',
    stores: 'เพิ่มสินค้า',
    kpi: 'ความสำเร็จ',
    reports: 'รายงาน',
    settings: 'ตั้งค่า',
    product: 'สินค้า',
    customer: 'ลูกค้า',
    createat: 'วันที่สร้าง',
    expiry: 'วันหมดอายุ',
    edit: 'แก้ไข',
    view: 'ดูข้อมูล',
    expenses: 'ค่าใช่จ่าย',
    budget: 'เงินลงทุน',
    balance: 'ยอดเงิน',
    productname: 'ชื่อสินค้า',
    price: 'ราคา',
    cost: 'ต้นทุน',
    type: 'ประเภท',
    upload: 'อัพโหลดภาพ',
    home: 'หน้าแรก',
    new: 'ใหม่',
    description: 'คำอธิบาย',
    email: 'อีเมล',
    password: 'รหัสผ่าน',
    newpassword: 'รหัสผ่านใหม่',
    confirmpassword: 'ยืนยันรหัสผ่าน',
    fieldname: 'ชื่อข้อมูล',
    options: 'ตัวเลือก',
    title: 'หัวข้อ',
    added: 'เพิ่มแล้ว',
    username: 'ชื่อผู้ใช้',
    notmatch: "การยืนยันรหัสผ่านไม่ถูกต้อง",
    required: "จำเป็นต้องกรอกข้อมูล",
    web: "เว็บ",
    login: "เข้าสู่ระบบ",
    logout: "ออกจากระบบ",
    register: "สมัครสมาชิก",
    types: "เพิ่มประเภท",
    submit:"ลงทะเบียน",
    update:"อัพเดทข้อมูล",
    promotions:"เพิ่มโปรโมชั่น",
    value:"ค่า",
    remainingdays:"จำนวนวันคงเหลือ"
  },
  {
    id: 'ID',
    name: 'Name',
    memo: 'Memo',
    date: 'Date',
    lang: 'English',
    dashboard: 'Dashboard',
    creates: 'Creates',
    products: 'Add Products',
    stores: 'Add Stores',
    kpi: 'Achievement',
    reports: 'Reposts',
    settings: 'Settings',
    product: 'Product',
    customer: 'Customer',
    createat: 'Create At',
    expiry: 'Expiry',
    edit: 'Edit',
    view: 'View',
    expenses: 'Total Expenses',
    budget: 'Total Budget',
    balance: 'Total Balance',
    productname: 'Product Name',
    price: 'Sale Price',
    cost: 'Cost',
    type: 'Type',
    upload: 'Upload Image',
    home: 'Home',
    new: 'new',
    description: 'Description',
    email: 'Email Address',
    password: 'Password',
    newpassword: 'New Password',
    confirmpassword: 'Confirm Password',
    fieldname: 'Field Name',
    options: 'Options',
    title: 'Title',
    added: 'Added',
    username: 'Username',
    notmatch: "Confirm password do not match",
    required: "is requires",
    web: "Web",
    login: "Log In",
    logout: "Log Out",
    register: "Register",
    types: "Add Types",
    submit:"SUBMIT",
    update:"UPDATE",
    promotions:"Add Promotion",
    value:"Value",
    remainingdays:"Remaining days"
  }
]

export default Lang;